version: "3"
services:
  skeleton-be:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_HOST=db
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=skeleton
      - MYSQL_USER=skeleton_user
      - MYSQL_PASSWORD=P@ssword123
    ports:
      - "3306:3306"
